export const docInfo = [
  {
    id: 'doc-001',
    name: 'Dr. Aisha Kamau',
    specialty: 'Cardiology',
    rating: 4.8,
    reviewCount: 120,
    experience: 10,
    location: 'Nairobi, Kenya',
    consultationFee: 3000,
    nextAvailable: '2025-07-23T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a',
    languages: ['English', 'Swahili'],
    verified: true,
    about: 'Experienced cardiologist with a decade of helping patients manage heart health.',
    education: [
      { degree: 'MBChB', institution: 'University of Nairobi', year: 2010 },
      { degree: 'MSc Cardiology', institution: 'Oxford University', year: 2014 },
    ],
    workExperience: [
      { hospital: 'Kenyatta National Hospital', years: 5 },
      { hospital: 'Aga Khan University Hospital', years: 5 },
    ],
    certifications: ['Kenya Medical Board', 'BLS', 'ACLS'],
    services: ['Heart Checkup', 'ECG', 'Stress Test'],
    reviews: [],
    stats: {
      patientsServed: 2000,
      yearsExperience: 10,
      successRate: 97,
      responseTime: '1h',
    },
  },
  {
    id: 'doc-002',
    name: 'Dr. Brian Otieno',
    specialty: 'Dermatology',
    rating: 4.6,
    reviewCount: 85,
    experience: 7,
    location: 'Mombasa, Kenya',
    consultationFee: 2500,
    nextAvailable: '2025-07-24T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e',
    languages: ['English'],
    verified: true,
    about: 'Dedicated to helping patients with skin conditions regain confidence.',
    education: [
      { degree: 'MBChB', institution: 'Moi University', year: 2012 },
      { degree: 'Diploma in Dermatology', institution: 'University of Cape Town', year: 2016 },
    ],
    workExperience: [
      { hospital: 'Coast General Hospital', years: 3 },
      { hospital: 'Private Practice', years: 4 },
    ],
    certifications: ['Kenya Medical Board'],
    services: ['Acne Treatment', 'Skin Biopsy', 'Allergy Testing'],
    reviews: [],
    stats: {
      patientsServed: 1500,
      yearsExperience: 7,
      successRate: 94,
      responseTime: '2h',
    },
  },
  {
    id: 'doc-003',
    name: 'Dr. Cynthia Mwikali',
    specialty: 'Pediatrics',
    rating: 4.9,
    reviewCount: 200,
    experience: 12,
    location: 'Kisumu, Kenya',
    consultationFee: 2800,
    nextAvailable: '2025-07-23T14:00:00Z',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    languages: ['English', 'Swahili', 'Luo'],
    verified: true,
    about: 'Trusted pediatrician focused on child wellness and immunization.',
    education: [
      { degree: 'MBChB', institution: 'University of Nairobi', year: 2008 },
      { degree: 'Pediatrics Residency', institution: 'Toronto SickKids Hospital', year: 2013 },
    ],
    workExperience: [
      { hospital: 'Gertrude’s Children’s Hospital', years: 6 },
      { hospital: 'Jaramogi Oginga Odinga Hospital', years: 6 },
    ],
    certifications: ['PALS', 'Kenya Pediatric Society'],
    services: ['Child Wellness', 'Vaccinations', 'Developmental Screening'],
    reviews: [],
    stats: {
      patientsServed: 2500,
      yearsExperience: 12,
      successRate: 98,
      responseTime: '30min',
    },
  },
  {
    id: 'doc-004',
    name: 'Dr. David Kimani',
    specialty: 'Orthopedics',
    rating: 4.5,
    reviewCount: 90,
    experience: 8,
    location: 'Nakuru, Kenya',
    consultationFee: 3200,
    nextAvailable: '2025-07-25T11:00:00Z',
    image: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    languages: ['English', 'Swahili'],
    verified: true,
    about: 'Specialist in bone and joint disorders, treating fractures and arthritis.',
    education: [
      { degree: 'MBChB', institution: 'Kenyatta University', year: 2011 },
      { degree: 'Orthopedic Surgery Fellowship', institution: 'University of Cape Town', year: 2016 },
    ],
    workExperience: [
      { hospital: 'Nakuru County Hospital', years: 5 },
      { hospital: 'Private Practice', years: 3 },
    ],
    certifications: ['Kenya Orthopedic Association'],
    services: ['Joint Replacement', 'Arthroscopy', 'Fracture Management'],
    reviews: [],
    stats: {
      patientsServed: 1800,
      yearsExperience: 8,
      successRate: 95,
      responseTime: '1.5h',
    },
  },
  {
    id: 'doc-005',
    name: 'Dr. Emily Njeri',
    specialty: 'Gynecology',
    rating: 4.7,
    reviewCount: 110,
    experience: 9,
    location: 'Eldoret, Kenya',
    consultationFee: 2900,
    nextAvailable: '2025-07-22T15:30:00Z',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    languages: ['English', 'Swahili'],
    verified: true,
    about: 'Supporting women’s health through expert gynecological care.',
    education: [
      { degree: 'MBChB', institution: 'Moi University', year: 2010 },
      { degree: 'Masters in Obstetrics and Gynecology', institution: 'University of Pretoria', year: 2015 },
    ],
    workExperience: [
      { hospital: 'Moi Teaching and Referral Hospital', years: 6 },
      { hospital: 'Private Practice', years: 3 },
    ],
    certifications: ['OGUK', 'Kenya Medical Board'],
    services: ['Prenatal Care', 'Pap Smear', 'Family Planning'],
    reviews: [],
    stats: {
      patientsServed: 2200,
      yearsExperience: 9,
      successRate: 96,
      responseTime: '45min',
    },
  },
  {
    id: 'doc-006',
    name: 'Dr. Felix Omondi',
    specialty: 'Neurology',
    rating: 4.4,
    reviewCount: 70,
    experience: 6,
    location: 'Thika, Kenya',
    consultationFee: 3500,
    nextAvailable: '2025-07-24T12:00:00Z',
    image: 'https://plus.unsplash.com/premium_photo-1661580574627-9211124e5c3f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    languages: ['English'],
    verified: true,
    about: 'Treating brain and nervous system disorders with care and innovation.',
    education: [
      { degree: 'MBChB', institution: 'University of Nairobi', year: 2013 },
      { degree: 'Neurology Fellowship', institution: 'Mayo Clinic', year: 2018 },
    ],
    workExperience: [
      { hospital: 'Thika Level 5 Hospital', years: 4 },
      { hospital: 'NeuroClinic Africa', years: 2 },
    ],
    certifications: ['Kenya Neurology Society'],
    services: ['EEG', 'Stroke Management', 'Headache Clinic'],
    reviews: [],
    stats: {
      patientsServed: 1100,
      yearsExperience: 6,
      successRate: 93,
      responseTime: '3h',
    },
  },
];
